### ISSUE TITLE
设置颜色的部分是否考虑hsv？

### ISSUE THREAD

**Issue by ToKiNoBug** [Teddy-van-Jerry/Fractal_Designer#8]
刚刚用了用，感觉设置颜色方面的功能非常全面，但是感觉rgba不是那么好控制，未必能调出想要的色彩。建议增加对hsva的支持

**Comment by Teddy-van-Jerry** [comment]
Yes, this has been put on the agenda. Currently I am working on the Chinese translation of the app, and after that version, I will set out to add the option HSVA. (It is established that it can be achieved by July.) I have not started dealing with that, so you are welcome to Pull Request!

是的，这已经排上了日程，目前正在推出中英文双语的版本，接下来就将处理 HSVA。（大概将在 7 月份推出）。我目前还没有着手开始，你也可以贡献代码直接 Pull Request 哦。

**Comment by Teddy-van-Jerry** [comment]
@ToKiNoBug Now the new design of Fractal Designer 6 will integrate this inside. Please check out at https://group.teddy-van-jerry.org/project/new-members-in-2021-summer-project. Thanks for your suggestions! It is estimated that the brand new FRD 6 will be released within one month. Before that, there will be the final version of FRD 5 as Fractal Designer 5.6.
